"use client";

import * as React from "react";

import {
  Loader2,
  Printer,
  TriangleAlert,
  X,
} from "lucide-react";

import {
  Button,
} from "@/components/ui/button";

import {
  Dialog,
} from "@/components/ui/dialog";

import {
  ReportDocument,
  type PrintableReportSettings,
} from "@/components/reports/ReportDocument";

import {
  createClient,
} from "@/lib/supabase/client";

import type {
  DashboardReport,
} from "@/lib/domain/dashboard";

import type {
  ExpenseReport,
} from "@/lib/domain/expenses";


type ReportPrintDialogProps = {
  isOpen:
    boolean;

  onClose:
    () => void;

  report:
    DashboardReport | null;

  expenseReport:
    ExpenseReport | null;

  businessId:
    string;

  businessName:
    string;

  currencyCode:
    string;
};


type SettingsRecord = {
  [key: string]:
    unknown;
};


const DEFAULT_SETTINGS:
  PrintableReportSettings = {
    paperSize:
      "A4",

    orientation:
      "portrait",

    title:
      "Sales & Financial Report",

    displayName:
      null,

    addressLine1:
      null,

    addressLine2:
      null,

    phone:
      null,

    email:
      null,

    footerMessage:
      "Generated by NOVA POS",

    showSummary:
      true,

    showSalesTrend:
      true,

    showPaymentBreakdown:
      true,

    showTopProducts:
      true,

    showRecentSales:
      true,

    showOperatingExpenses:
      true,

    showNetOperatingProfit:
      true,
  };


function stringValue(
  record:
    SettingsRecord,
  keys:
    string[],
) {
  for (
    const key
    of keys
  ) {
    const value =
      record[key];

    if (
      typeof value ===
        "string" &&
      value.trim()
    ) {
      return value.trim();
    }
  }

  return null;
}


function booleanValue(
  record:
    SettingsRecord,
  keys:
    string[],
  fallback:
    boolean,
) {
  for (
    const key
    of keys
  ) {
    const value =
      record[key];

    if (
      typeof value ===
      "boolean"
    ) {
      return value;
    }
  }

  return fallback;
}


function parseSettings(
  value:
    unknown,
): PrintableReportSettings {
  if (
    !value ||
    typeof value !==
      "object" ||
    Array.isArray(
      value,
    )
  ) {
    return DEFAULT_SETTINGS;
  }


  const record =
    value as
      SettingsRecord;


  const paper =
    stringValue(
      record,
      [
        "paper_size",
        "paperSize",
      ],
    );


  const orientation =
    stringValue(
      record,
      [
        "orientation",
      ],
    );


  return {
    paperSize:
      paper ===
        "Letter"
        ? "Letter"
        : "A4",

    orientation:
      orientation ===
        "landscape"
        ? "landscape"
        : "portrait",

    title:
      stringValue(
        record,
        [
          "report_title",
          "title",
        ],
      ) ??
      DEFAULT_SETTINGS.title,

    displayName:
      stringValue(
        record,
        [
          "display_name",
          "business_display_name",
        ],
      ),

    addressLine1:
      stringValue(
        record,
        [
          "address_line_1",
        ],
      ),

    addressLine2:
      stringValue(
        record,
        [
          "address_line_2",
        ],
      ),

    phone:
      stringValue(
        record,
        [
          "phone",
        ],
      ),

    email:
      stringValue(
        record,
        [
          "email",
        ],
      ),

    footerMessage:
      stringValue(
        record,
        [
          "footer_message",
        ],
      ) ??
      DEFAULT_SETTINGS.footerMessage,

    showSummary:
      booleanValue(
        record,
        [
          "show_summary",
        ],
        true,
      ),

    showSalesTrend:
      booleanValue(
        record,
        [
          "show_sales_trend",
        ],
        true,
      ),

    showPaymentBreakdown:
      booleanValue(
        record,
        [
          "show_payment_breakdown",
        ],
        true,
      ),

    showTopProducts:
      booleanValue(
        record,
        [
          "show_top_products",
        ],
        true,
      ),

    showRecentSales:
      booleanValue(
        record,
        [
          "show_recent_sales",
          "show_transactions",
        ],
        true,
      ),

    showOperatingExpenses:
      booleanValue(
        record,
        [
          "show_operating_expenses",
        ],
        true,
      ),

    showNetOperatingProfit:
      booleanValue(
        record,
        [
          "show_net_operating_profit",
        ],
        true,
      ),
  };
}


export function ReportPrintDialog({
  isOpen,
  onClose,
  report,
  expenseReport,
  businessId,
  businessName,
  currencyCode,
}: ReportPrintDialogProps) {
  const [
    settings,
    setSettings,
  ] =
    React.useState<
      PrintableReportSettings
    >(
      DEFAULT_SETTINGS,
    );


  const [
    loading,
    setLoading,
  ] =
    React.useState(
      false,
    );


  const [
    error,
    setError,
  ] =
    React.useState<
      string | null
    >(null);


  React.useEffect(() => {
    if (
      !isOpen ||
      !businessId
    ) {
      return;
    }


    let cancelled =
      false;


    async function load() {
      setLoading(
        true,
      );


      setError(
        null,
      );


      try {
        const supabase =
          createClient();


        const {
          data,
          error:
            settingsError,
        } =
          await supabase
            .from(
              "report_settings",
            )
            .select(
              "*",
            )
            .eq(
              "business_id",
              businessId,
            )
            .maybeSingle();


        if (
          settingsError
        ) {
          throw new Error(
            settingsError.message,
          );
        }


        if (
          !cancelled
        ) {
          setSettings(
            parseSettings(
              data,
            ),
          );
        }
      } catch (cause) {
        if (
          !cancelled
        ) {
          setSettings(
            DEFAULT_SETTINGS,
          );


          setError(
            cause instanceof
            Error
              ? cause.message
              : "Report settings could not be loaded.",
          );
        }
      } finally {
        if (
          !cancelled
        ) {
          setLoading(
            false,
          );
        }
      }
    }


    void load();


    return () => {
      cancelled =
        true;
    };
  }, [
    businessId,
    isOpen,
  ]);


  function handlePrint() {
    window.print();
  }


  return (
    <Dialog
      isOpen={
        isOpen
      }
      onClose={
        onClose
      }
      title="Print Report"
      description="NOVA generates a separate print-ready financial document instead of printing the dashboard screen."
      className="max-h-[calc(100dvh-1rem)] max-w-6xl overflow-hidden"
      hideCloseButton
    >

      <div className="flex max-h-[calc(100dvh-9rem)] flex-col">

        <div className="mb-4 flex shrink-0 items-center justify-between gap-4">

          <div>

            <p className="text-sm font-semibold">
              Print Preview
            </p>


            <p className="mt-1 text-xs text-muted-foreground">
              {
                settings.paperSize
              }{" "}
              ·{" "}
              {
                settings.orientation
              }
            </p>

          </div>


          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="rounded-[12px]"
            onClick={
              onClose
            }
          >

            <X className="h-4 w-4" />

          </Button>

        </div>


        {error && (

          <div className="mb-4 flex shrink-0 items-start gap-2 rounded-[14px] border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-700 dark:text-amber-300">

            <TriangleAlert className="mt-0.5 h-4 w-4 shrink-0" />


            <span>
              NOVA could not load custom report settings, so default print settings are being used.{" "}
              {
                error
              }
            </span>

          </div>

        )}


        <div className="min-h-0 flex-1 overflow-y-auto rounded-[18px] bg-muted/50 p-4 sm:p-6">

          {loading ? (

            <div className="flex min-h-[400px] flex-col items-center justify-center">

              <Loader2 className="h-7 w-7 animate-spin text-primary" />


              <p className="mt-3 text-sm text-muted-foreground">
                Preparing report…
              </p>

            </div>

          ) : report &&
            expenseReport ? (

            <ReportDocument
              report={
                report
              }
              expenseReport={
                expenseReport
              }
              businessName={
                businessName
              }
              currencyCode={
                currencyCode
              }
              settings={
                settings
              }
            />

          ) : (

            <div className="flex min-h-[400px] items-center justify-center text-sm text-muted-foreground">
              Report data is unavailable.
            </div>

          )}

        </div>


        <div className="mt-4 flex shrink-0 justify-end gap-2 border-t bg-background pt-4">

          <Button
            type="button"
            variant="outline"
            className="rounded-[12px]"
            onClick={
              onClose
            }
          >
            Cancel
          </Button>


          <Button
            type="button"
            className="rounded-[12px]"
            disabled={
              loading ||
              !report ||
              !expenseReport
            }
            onClick={
              handlePrint
            }
          >

            <Printer className="mr-2 h-4 w-4" />

            Print / Save PDF

          </Button>

        </div>

      </div>

    </Dialog>
  );
}